language: python
python:
  - 2.7
install:
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  - sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
  - sudo apt-get update
  - sudo apt-get install google-chrome-stable
  - wget http://chromedriver.storage.googleapis.com/2.7/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - sudo ln chromedriver /bin/chromedriver
  - python bootstrap.py
  - bin/buildout
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script: 
  - bin/pybot tests/
